### ISSUE TITLE
Make a final release supporting 2.7, then stop supporting EOL versions of Python

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1276]
**Description of issue or feature request**:

Cryptography is the latest one of our dependencies to [drop support for Python 2.7](https://cryptography.io/en/latest/changelog.html#v3-4), and one that seems unwise to try and pin. Given that the Python ecosystem, including many of our dependencies, continue to drop support for Python 2.7 it seems prudent to make a 'final' Python 2.7 supporting release so that we can stop worrying about whether dependency updates affect our ability to support Python 2.7, and instead can focus on [moving the codebase forwards](https://github.com/theupdateframework/tuf/projects/2).

**Current behavior**:

We continue to try and support Python 2.7 with the current codebase, despite many of our dependencies dropping support and that version of Python being EOL. This often results in pinning dependencies to Python 2.7 supported versions, which will prevent us from updating for security, and other bug, fixes.

**Expected behavior**:

Make one final release supporting Python 2.7, then drop support in future releases. We can create a branch from the tag of this final 2.7 supporting release should we want to integrate updates to that release in future.

**Tasks**
- [x] make a release of the current code
- [ ] drop Python 2.7 from `setup.py`, GitHub Actions workflows, requirements files, dependabot config, and other places.
- [ ] update documentation (including ADR0001?)

**Comment by trishankatdatadog** [comment]
Thanks for tracking this issue! This one needs some yelling as loudly as possible on our mailing lists, GitHubs, Slacks, Twitters, etc...

**Comment by trishankatdatadog** [comment]
Otherwise, we risk running into surprises like [this](https://github.com/pyca/cryptography/issues/5771)...
