### ISSUE TITLE
Remove `MetadataWrapper` class

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1304]
I find it a bit paradox that `MetadataWrapper` is another container on top of `Metadata`, adding another level of nesting, when most of the methods/properties are actually shortcuts to attributes contained somewhere in `Metadata`. If we want a client-variant of `Metadata`, I'd maybe use inheritance instead of composition. 🤷 

But maybe we don't even need it. Let's quickly go through the individual methods/properties of here:

On `MetadataWrapper`:

- `from_json_file` -> available as `Metadata.from_file` with json as default (#1279)
- `from_json_object` -> could be a format-agnostic method on `Metadata` just like `from_file`. #1336 
- `persist` ->  available as `Metadata.to_file` with json as default (#1279)
- `expires` -> could be a method on `Signed`, I'd call it 'is_expired' #1305 
- `verify` -> This is definitely needed for the repository tool as well. So it should be somewhere where both client and repository tool can access it. Maybe even on `Metadata` in addition to the vanilla  one-signature `verify` we currently have. See https://github.com/theupdateframework/tuf/pull/1060#issuecomment-660056376 for thoughts about that distinction. #1306

All the other methods here are either pure shortcuts or filters of attributes contained in Metadata objects (or contained objects).

- Re **shortcuts**: https://github.com/theupdateframework/tuf/pull/1060/files#r452906629 has arguments against shortcuts.
- Re **filters**: Maybe it will become easier to access individual properties once we have classes for all complex attributes as planned in https://github.com/theupdateframework/tuf/issues/1139? But similarly to the arguments against shortcuts, I'd be careful when implementing behavior that relates to contained classes on container classes.

_Originally posted by @lukpueh in https://github.com/theupdateframework/tuf/pull/1291#discussion_r590391070_

**Comment by sechkova** [comment]
Steps that I suggest should be followed for completing this issue:

- [x] ~Implement from_object method in Metadata class~ #1336
- [x] ~Implement 'expired' method in Signed class~ #1305
- [ ] Implement verification by a threshold of keys #1306
- [ ] Replace calls to `MetadataWrapper.from_json_file` with the available `Metadata.from_file`
- [ ] Replace calls to `MetadataWrapper.from_json_object` with  the newly implemented `Metadata.from_object`
- [ ] Replace calls to `MetadataWrapper.persist` with the available `Metadata.to_file`
- [ ] Replace calls to `MetadataWrapper.expires` with the newly implemented 'expired'
- [ ] Replace calls to  `MetadataWrapper.verify` with the newly implemented verification
- [ ] Remove shortcuts and filters (see the issue description)
- [ ] Remove the MetadataWrapper class itself

**Comment by sechkova** [comment]
All the steps above will be completed withe the merge of #1355 and #1396.

**Comment by sechkova** [comment]
Done with #1355 and #1396.
